<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree $tree
 */
?>

<h2>Main Title</h2>
<div>
<p><strong>An HTML block with multiple collapsing sections, ready to add your own content, edit and extend.</strong></p>
    
<div>
    
<div class="compact__section closer"><a class="closer compact__section__title" href="#section-0">compact</a>
<div class="compact__section__content" id="section-0">&nbsp;</div>
</div>

<div class="compact__section"><a class="compact__section__title" href="#section-1">Section 1</a>
<div class="compact__section__content" id="section-1">
<h2>Title 1</h2>
<hr />
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit mauris quis risus molestie, in interdum risus faucibus. Donec eu rhoncus ligula. Sed quis blandit ex. Nullam facilisis consectetur erat sed ultrices. Pellentesque consectetur condimentum quam, sed auctor nulla pellentesque et. Suspendisse tempus pharetra purus, eget vulputate lorem efficitur nec. Praesent tincidunt, lectus ut fringilla sagittis, dolor ex tempus mi, nec dictum ante felis vel odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras in commodo libero. Vestibulum commodo massa quis enim facilisis mollis. Vivamus efficitur, lacus non consectetur eleifend, ex dui dignissim arcu.</p>
</div>
</div>

<div class="compact__section"><a class="compact__section__title" href="#section-2">Section 2</a>

<div class="compact__section__content" id="section-2">
<h2>Title 2</h2>
<hr />    
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit mauris quis risus molestie, in interdum risus faucibus. Donec eu rhoncus ligula. Sed quis blandit ex. Nullam facilisis consectetur erat sed ultrices. Pellentesque consectetur condimentum quam, sed auctor nulla pellentesque et. Suspendisse tempus pharetra purus, eget vulputate lorem efficitur nec. Praesent tincidunt, lectus ut fringilla sagittis, dolor ex tempus mi, nec dictum ante felis vel odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras in commodo libero. Vestibulum commodo massa quis enim facilisis mollis. Vivamus efficitur, lacus non consectetur eleifend, ex dui dignissim arcu.</p>
</div>
</div>

<div class="compact__section"><a class="compact__section__title" href="#section-3">Section 3</a>
<div class="compact__section__content" id="section-3">
<h2>Title 3</h2>

<hr />
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit mauris quis risus molestie, in interdum risus faucibus. Donec eu rhoncus ligula. Sed quis blandit ex. Nullam facilisis consectetur erat sed ultrices. Pellentesque consectetur condimentum quam, sed auctor nulla pellentesque et. Suspendisse tempus pharetra purus, eget vulputate lorem efficitur nec. Praesent tincidunt, lectus ut fringilla sagittis, dolor ex tempus mi, nec dictum ante felis vel odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras in commodo libero. Vestibulum commodo massa quis enim facilisis mollis. Vivamus efficitur, lacus non consectetur eleifend, ex dui dignissim arcu.</p>
</div>
</div>

<div class="compact__section"><a class="compact__section__title" href="#section-4">Section 4</a>

<div class="compact__section__content" id="section-4">
<h2>Title 4</h2>

<hr />
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit mauris quis risus molestie, in interdum risus faucibus. Donec eu rhoncus ligula. Sed quis blandit ex. Nullam facilisis consectetur erat sed ultrices. Pellentesque consectetur condimentum quam, sed auctor nulla pellentesque et. Suspendisse tempus pharetra purus, eget vulputate lorem efficitur nec. Praesent tincidunt, lectus ut fringilla sagittis, dolor ex tempus mi, nec dictum ante felis vel odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras in commodo libero. Vestibulum commodo massa quis enim facilisis mollis. Vivamus efficitur, lacus non consectetur eleifend, ex dui dignissim arcu.</p>
</div>
</div>

<div class="compact__section"><a class="compact__section__title" href="#section-5">Section 5</a>
<div class="compact__section__content" id="section-5">
<h2>Title 5</h2>

<hr />
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit mauris quis risus molestie, in interdum risus faucibus. Donec eu rhoncus ligula. Sed quis blandit ex. Nullam facilisis consectetur erat sed ultrices. Pellentesque consectetur condimentum quam, sed auctor nulla pellentesque et. Suspendisse tempus pharetra purus, eget vulputate lorem efficitur nec. Praesent tincidunt, lectus ut fringilla sagittis, dolor ex tempus mi, nec dictum ante felis vel odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras in commodo libero. Vestibulum commodo massa quis enim facilisis mollis. Vivamus efficitur, lacus non consectetur eleifend, ex dui dignissim arcu.</p>
</div>
</div> 
    
</div>
</div>
<div class="compact__section to-top"><a class="compact__section__title" href="#section-0">compact to top</a>
    <div class="compact__section__content" id="bottom">&nbsp;</div>
</div>  
