<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

/**
 * @var string               $html
 * @var array<int,string>    $languages
 * @var bool                 $show_timestamp
 * @var array<string,string> $templates
 * @var string               $title
 */

?>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="title">
        <?= I18N::translate('Title') ?>
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" id="title" name="title" value="<?= e($title) ?>">
    </div>
</div>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="template">
        <?= I18N::translate('Templates') ?>
    </label>
    <div class="col-sm-9">
        <?= view('components/select', ['name' => '', 'id' => 'template', 'selected' => '', 'options' => $templates]) ?>
        <p>
            <?= I18N::translate('Choosing <b>Accordion Starter</b> from the <b>Template</b> dropdown will load the content of default webtrees HTML Block templates inside collapsable accordion sections. The first section contains a ReadMe with more information. Add a <b>Title</b> and <b>Save</b>. View the result in the <b>HTML Compact Block</b> you have added to your <b>My Page</b> or <b>Tree Home Page</b>.<br>
            The <b>Vanilla</b> template is just the collapsible sections with Lorem ipsum placeholder text.
            More templates to come.') ?>
        </p>
    </div>
</div>

<div class="row mb-3">
    <label class="col-sm-3 col-form-label" for="html">
        <?= I18N::translate('Content') ?>
    </label>
    <div class="col-sm-9">
        <p>
            <?= I18N::translate('You can use the editor toolbar to apply HTML formatting to your content. Advanced users can use the <b>Source</b> tab to access HTML code for editing content. There you can apply webtrees CSS classes to your content for more integrated styling. You can also insert special database fields which are updated automatically. These fields are marked with <b>#</b> characters. For example <b>#totalFamilies#</b> will be replaced with the actual number of families in the database. Using the <b>Source</b> you can also add more sections. See the ReadMe in the first starter section for important information on that.') ?>
        </p>
        <textarea name="html" id="html" class="html-edit form-control" rows="10"><?= e($html) ?></textarea>
    </div>
</div>

<fieldset class="row mb-3">
    <legend class="col-form-label col-sm-3">
        <?= I18N::translate('Show the date and time of update') ?>
    </legend>
    <div class="col-sm-9">
        <?= view('components/radios-inline', ['name' => 'show_timestamp', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int) $show_timestamp]) ?>
    </div>
</fieldset>

<fieldset class="row mb-3">
    <legend class="col-form-label col-sm-3">
        <?= I18N::translate('Show this block for which languages') ?>
    </legend>
    <div class="col-sm-9">
        <?= view('edit/language-checkboxes', ['languages' => $languages]) ?>
    </div>
</fieldset>

<?php View::push('javascript') ?>
<script>
    $("#template").change(function () {
        this.form.html.value=this.options[this.selectedIndex].value;
        CKEDITOR.instances.html.setData(document.getElementById("html").value);
    });
</script>
<?php View::endpush() ?>
